export enum TTS_SPEEDS {
  SLOW = 0.5,
  MEDIUM = 0.75,
  NORMAL = 1,
  FAST = 1.25,
  FASTER = 1.5,
  FASTEST = 2,
}
export const SPEEDS = [
  TTS_SPEEDS.SLOW,
  TTS_SPEEDS.MEDIUM,
  TTS_SPEEDS.NORMAL,
  TTS_SPEEDS.FAST,
  TTS_SPEEDS.FASTER,
  TTS_SPEEDS.FASTEST,
];
